/*
 * This file was autogenerated by TinyMPC on Tue Nov 14 05:15:07 2023
 */

#pragma once

#include "types.hpp"

#ifdef __cplusplus
extern "C" {
#endif

extern TinySolver tiny_data_solver;

#ifdef __cplusplus
}
#endif
